### ISSUE TITLE
Modal content not scrollable on small viewports

### ISSUE THREAD

**Issue by decause** [DevProgress/mazza#3]
On mobile when viewing content in the modals, longer content runs off the bottom of the screen and there's no way to scroll to see it. This is the result on iPhone 6s:

![image](https://cloud.githubusercontent.com/assets/3196550/18138833/82d79a82-6f63-11e6-91f0-f4cbb316f8f4.png)

Propose fixing height of modal on small viewports and scrolling content within modal.

**Comment by decause** [comment]
Confirmed Reproductions:
- iPhone 6 Plus, iOS 9.
- iPhone 6 Plus, iOS 9.3.5
- iPhone 5, iOS 10

**Comment by decause** [comment]
Suggested fixes: 
- Make the Modal Full-screen
- Fix modal size
- Load the <code>states-data.json</code> sooner in <code>index.html</code>

**Comment by otech47** [comment]
Why is the body set to `overflow: hidden` when the modal is open? If it's necessary, then I also don't see any element on the modal with an `overflow-y: scroll` property which seems like what you need to be able to see content that runs off the bottom of the screen.

**Comment by jtbandes** [comment]
When the modal is open, `<body>` gets the `.modal-open` class. `.modal-open .modal` has `overflow-y: auto`.

**Comment by otech47** [comment]
I would try explicitly setting `overflow-y: scroll` somewhere on the modal. Not sure which element exactly, but play with all of them. Should be the either the parent,  or the parent of the parent (grandparent?) of whichever elements' heights actually contribute to the overflow

**Comment by jtbandes** [comment]
In Slack we've just found a way to reliably reproduce the issue: delay loading of the images. It's triggered when image loading (or anything) causes a delayed size change in the modal dialog.
